name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # triggers on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build project
      run: |
        pyinstaller --onefile main.py

    - name: Create release artifacts
      run: |
        mkdir -p artifacts
        cp dist/* artifacts/

    - name: Upload release assets
      uses: actions/upload-artifact@v2
      with:
        name: release-artifacts
        path: artifacts/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: release-artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}